---
openapi: 3.0.3
info:
  title: short-form-video-api
  description: The API for the Short Form video project
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/2458862813/ProjSFV/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://{ip}:{port}
  description: Short Form video API
  variables:
    ip:
      description: ip Adress
      default: 192.168.1.1
    port:
      description: port
      default: "8080"
paths:
  /user:
    post:
      tags:
      - User
      summary: 用户注册
      operationId: register
      requestBody:
        $ref: '#/components/requestBodies/UserDTO'
      responses:
        "200":
          description: 注册成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBody'
              example:
                code: 200
                message: register success!
        "400":
          description: 注册失败,用户名称已经存在或者手机号邮箱使用到上限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBody'
              example:
                message: 用户名存在
  /user/login:
    post:
      tags:
      - User
      summary: 用户登陆
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_login_body'
        required: true
      responses:
        "200":
          description: 登陆成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBody'
              example:
                code: 200
                data: '{"token": "412312312edsfadf" }'
        "401":
          description: 登陆失败，会返回结果是用户名不存在或者是密码错误
          content:
            application/json:
              example:
                message: 用户名不存在
  /user/{id}:
    get:
      tags:
      - User
      summary: 获取用户信息
      description: 获取用户自己的信息
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          example: 1
      - name: Authorization
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 成功获取用户信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "402":
          description: 查询用户信息失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_402'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
    put:
      tags:
      - User
      summary: 修改用户信息
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: 修改用户信息成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "405":
          description: 修改用户信息失败，用户名称存在，或者是权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_405'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
    delete:
      tags:
      - User
      summary: 删除用户
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
        example: 1
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
        example: fff
      responses:
        "200":
          description: 成功删除用户，返回id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
  /user/search/{user}:
    get:
      tags:
      - User
      summary: 查找用户
      description: 用于客户端查找用户
      parameters:
      - name: user
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        examples:
          phone:
            description: 手机号搜索
            value: 15837651231
          id:
            description: id搜索
            value: 1000001
          userName:
            description: 用户名搜索
            value: cherish
      responses:
        "200":
          description: 成功，返回结果id，头像，昵称，签名，性别，现居地
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
        "403":
          description: 查找用户失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
  /user/basicInfo/{id}:
    get:
      summary: 获取用户基本信息
      description: 用于获取用户基本信息，不需要token
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
        - name: token
          in: header
          required: false
          style: simple
          explode: false
          schema:
            type: string
            format: uuid
      responses:
        200:
            description: 成功，返回结果id，头像，昵称，签名，性别，现居地，关注数，粉丝数，获得点赞数目
            content:
                application/json:
                  schema:
                    properties:
                      data:
                        $ref: "#/components/schemas/UserBasicInfo"
        406:
          $ref: "#/components/responses/PermissionDenied"
  /user/logout/{id}:
    get:
      tags:
      - User
      summary: 用户登出（使得token失效）
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: 登出成功
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
  /user/profile/{id}:
    get:
      tags:
      - User
      summary: 获取用户历史头像
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 获取用户历史头像成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
    put:
      tags:
      - User
      summary: 修改用户头像
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          img/png:
            schema:
              $ref: '#/components/schemas/profile_id_body'
      responses:
        "200":
          description: 头像修改成功
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
  /user/friends/{id}:
    get:
      tags:
      - Socializing
      - User
      summary: 获得用户的好友列表
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 1
      responses:
        "200":
          description: 返回用户好友列表，单页长度不超过20
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
    post:
      tags:
      - User
      - Socializing
      summary: 加(删除)用户好友
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/friends_id_body'
      responses:
        "200":
          description: 发送好友邀请成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
  /user/friends/{id1}/{id2}:
    delete:
      tags:
      - Socializing
      - User
      summary: 删除好友关系
      parameters:
      - name: id1
        in: path
        description: 当前用户id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: id2
        in: path
        description: 删除好友的id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 删除好友关系成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_7'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
      deprecated: true
  /user/fans/{id}:
    get:
      tags:
      - Socializing
      - User
      summary: 获得用户的粉丝列表
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 1
      responses:
        "200":
          description: 获取粉丝列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_8'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
  /user/subscriber/{id}:
    get:
      tags:
      - User
      - Socializing
      summary: 获得用户的关注列表
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 1
      responses:
        "200":
          description: 获取关注列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_8'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
    post:
      tags:
      - User
      - Socializing
      summary: 关注其他用户
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subscriber_id_body'
      responses:
        "200":
          description: 关注成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_9'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
  /user/blocked/{id}:
    get:
      tags:
      - User
      - Socializing
      summary: 查询用户黑名单
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 查询黑名单成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_8'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
    post:
      tags:
      - User
      - Socializing
      summary: 将用户加入(删除)黑名单
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/blocked_id_body'
      responses:
        "200":
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                删除成功:
                  value:
                    message: 将xxx从黑名单移除成功
                添加成功:
                  value:
                    message: 将xxx添加到黑名单成功
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
  /video:
    post:
      tags:
      - Video
      summary: 上传视频
      parameters:
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoDTO'
      responses:
        "200":
          description: 提交成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_10'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
        "500":
          description: 服务器上传失败
  /video/{id}:
    put:
      tags:
      - Video
      summary: 修改视频信息
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: av1
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoDTO'
      responses:
        "200":
          description: 修改成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_10'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
    delete:
      tags:
      - Video
      summary: 删除视频
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
        example: 1
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: 删除成功
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                越权:
                  value:
                    message: 你没有操作权限
                过期:
                  value:
                    message: token过期
  /video/collection/{id}:
    get:
      tags:
      - Video
      summary: 获得用户所有的收藏类目
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: 成功获得所有类目
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_11'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
  /video/collection/{id}/{collector}:
    get:
      tags:
      - Video
      summary: 获取用户的收藏
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: collector
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 默认
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
        example: 1
      responses:
        "200":
          description: 获取用户收藏成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_12'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
  /video/like/{id}:
    get:
      tags:
      - Video
      summary: 获取用户喜爱列表
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 获取用户喜爱列表成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_13'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
    post:
      tags:
      - Video
      summary: 添加(删除)喜欢视频
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/like_id_body'
            examples:
              添加喜欢:
                value:
                  id: av1
                  message: insert
              删除喜欢:
                value:
                  id: av1
                  message: delete
      responses:
        "200":
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                添加成功:
                  value:
                    message: 添加xxx为喜欢成功
                删除成功:
                  value:
                    message: 删除xxx为喜欢成功
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
  /video/dislike/{id}:
    get:
      tags:
      - Video
      summary: 获取用户不喜爱列表
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 获取用户不喜爱列表成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_13'
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
    post:
      tags:
      - Video
      summary: 添加(删除)不喜欢视频
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dislike_id_body'
            examples:
              添加不喜欢:
                value:
                  id: av1
                  message: insert
              删除不喜欢:
                value:
                  id: av1
                  message: delete
      responses:
        "200":
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                添加成功:
                  value:
                    message: 添加xxx为不喜欢成功
                删除成功:
                  value:
                    message: 删除xxx为不喜欢成功
        "406":
          description: 权限错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
              examples:
                token失效:
                  value:
                    message: token失效
                越权:
                  value:
                    message: 没有操作权限
components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        userName:
          maxLength: 32
          minLength: 5
          type: string
          example: cherish
        signature:
          maxLength: 128
          minLength: 0
          type: string
          nullable: true
        phoneNumber:
          pattern: /d11
          type: string
          example: "13691231233"
        gender:
          type: boolean
          description: true for man, false for woman
          nullable: false
        email:
          type: string
          format: email
          example: example@qq.com
        qqNumber:
          maximum: 12
          type: string
          format: qq number
          nullable: true
          example: "2458862813"
        wxNumber:
          maximum: 20
          type: string
          format: wechat number
          example: cherishyyy
        ipAdress:
          type: integer
          format: ip address
          nullable: true
        profile:
          type: string
          format: base64
        currentAdress:
          maximum: 32
          type: string
          nullable: true
          example: 河南信阳
        homeTown:
          maximum: 32
          type: string
          nullable: true
          example: 河南信阳
        graduatedSchool:
          maximum: 32
          type: string
          nullable: true
          example: 福建师范大学
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        userName:
          maxLength: 32
          minLength: 5
          type: string
          example: cherish
        signature:
          maxLength: 128
          minLength: 0
          type: string
          nullable: true
        phoneNumber:
          pattern: /d11
          type: string
          example: "13691231233"
        gender:
          type: boolean
          description: true for man, false for woman
          nullable: false
          example: true
        email:
          type: string
          format: email
          example: example@qq.com
        qqNumber:
          maximum: 12
          type: string
          format: qq number
          nullable: true
          example: "2458862813"
        wxNumber:
          maximum: 20
          type: string
          format: wechat number
          example: cherishyyy
        ipAdress:
          type: integer
          format: ip address
          nullable: true
        profile:
          type: string
          format: base64
        currentAdress:
          maximum: 32
          type: string
          nullable: true
          example: 河南信阳
        homeTown:
          maximum: 32
          type: string
          nullable: true
          example: 河南信阳
        graduatedSchool:
          maximum: 32
          type: string
          nullable: true
          example: 福建师范大学
    UserFriendVo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userName:
          type: string
        signature:
          type: string
        sex:
          type: boolean
        currentIPAdress:
          type: string
      example:
        id: 1
        userName: cherish
        currentIPAddress: 上海
        signature: 我喜欢自由
        sex: 0
    ResponseBody:
      type: object
      properties:
        code:
          type: integer
          format: int32
          nullable: false
          example: 200
        data:
          type: string
          format: json
          example: '{"name": "cherish"}'
        message:
          type: string
          description: another message
          nullable: true
    SearchResultItem:
      properties:
        id:
          type: integer
          format: int64
          example: 1
        userName:
          type: string
          example: cherish
        signature:
          type: string
          example: I love Java!
        gender:
          type: boolean
          description: true是男生，false是女生
          example: true
        currenAddress:
          type: string
          example: 福建福州
        profile:
          type: string
          format: base64
      description: 搜索成功后的结果
    VideoDTO:
      properties:
        videoName:
          type: string
        authorId:
          type: integer
          format: int64
        videoProfile:
          type: string
          format: base64
        submitTime:
          type: object
        isPublished:
          type: boolean
        isDeleted:
          type: boolean
        tags:
          type: string
        description:
          type: string
      description: 用户提交视频
      example:
        videoName: 第一个视频
        authorId: 1
        submitTime: 2023.2.18
        isPublished: true
        isDeleted: false
        tags: '#搞笑#好玩'
        description: 发布的第一个视频纪念
    Video:
      properties:
        videoName:
          type: string
        authorName:
          type: string
        videoProfileUrl:
          type: string
        length:
          type: integer
          description: 视频长度，单位s
          format: int32
        likeCount:
          type: integer
          format: int32
        commentId:
          type: string
        submitTime:
          type: object
        tags:
          type: string
        description:
          type: string
      description: 视频实体，返回给用户的描述部分
      example:
        videoName: 第一个视频
        authorName: Cherish
        videoProfileUrl: https://cherishyyy.xyz/1.jpg
        length: 59
        likeCount: 2
        commentId: 1
        submitTime: 2023.2.18
        tags: '#搞笑#好玩'
        description: 发布的第一个视频纪念
    VideoLikeVo:
      properties:
        videoId:
          type: string
        videoName:
          type: string
        tags:
          type: array
          items:
            type: string
            example: 美食
        profileUrl:
          type: string
      description: 用户喜欢（收藏）视频的Vo
      example:
        videoId: av1
        videoName: 我爱中国
        tags:
        - 美食
        - 中国
        - 爱国
        profileUrl: https://cherishyyy.xyz/1.jpg
    Profile:
      type: object
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
      example:
        id: 1
        url: https://cherishyyy.xyz/1.jpg
    UserBasicInfo:
      properties:
        id:
          type: integer
          format: int64
        profile:
          type: string
          format: base64
        userName:
          type: string
        signature:
          type: string
        gender:
          type: boolean
          description: true是男生，false是女生
        currentAddress:
          type: string
        subscribedCount:
          type: integer
          format: int64
        fansCount:
          type: integer
          format: int64
        likeCount:
          type: integer
          format: int64
      example:
        id: 1
        profile: https://cherishyyy.xyz/1.jpg
        userName: cherish
        signature: 我爱中国
        gender: true
        currentAddress: 福建福州
        subscribedCount: 1
        fansCount: 1
        likeCount: 1
    user_login_body:
      properties:
        user:
          maxLength: 32
          minLength: 5
          type: string
          description: 用户名或id或者手机号
          example: cherish
        password:
          maxLength: 16
          minLength: 8
          type: string
          example: passsword123
    inline_response_200:
      properties:
        message:
          type: string
          example: 成功获取用户信息
        data:
          $ref: '#/components/schemas/User'
    inline_response_402:
      properties:
        message:
          type: string
          example: 用户权限不足
    inline_response_406:
      properties:
        message:
          type: string
    inline_response_200_1:
      properties:
        message:
          type: string
          example: update success!
        data:
          type: string
          format: json
          example: '{"username":"cherishyyy"}'
    inline_response_405:
      properties:
        message:
          type: string
          example: 用户名存在
        data:
          type: string
          format: json
    inline_response_200_2:
      properties:
        message:
          type: string
        data:
          type: object
          example:
            id: 1
    inline_response_200_3:
      properties:
        message:
          type: string
          nullable: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/SearchResultItem'
    inline_response_403:
      properties:
        message:
          type: string
          example: 你最近查找太多次了
        data:
          type: string
          format: json
    inline_response_200_4:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Profile'
    profile_id_body:
      properties:
        newProfile:
          type: string
          format: base64
    inline_response_200_5:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/UserFriendVo'
    friends_id_body:
      properties:
        id:
          type: integer
          format: int6
        message:
          type: string
          enum:
          - request
          - accept
          - delete
    inline_response_200_6:
      properties:
        message:
          type: string
          example: 发送好友邀请成功
    inline_response_200_7:
      properties:
        message:
          type: string
          example: xxx已经不是你的好友
    inline_response_200_8:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/UserFriendVo'
    subscriber_id_body:
      properties:
        id:
          type: integer
          format: int64
    inline_response_200_9:
      properties:
        message:
          type: string
          example: xxx已经关注成功
    blocked_id_body:
      properties:
        id:
          type: integer
          format: int64
        message:
          type: string
          enum:
          - request
          - free
      example:
        id: 1
        message: request
    inline_response_200_10:
      properties:
        Authorization:
          type: string
          example: q-sign-algorithm=sha1&q-ak=AKIDQjz3ltompVjBni5LitkWHFlFpwkn****&q-sign-time=1557989753;1557996953&q-key-time=1557989753;1557996953&q-header-list=date;host&q-url-param-list=response-cache-control;response-content-type&q-signature=01681b8c9d798a678e43b685a9f1bba0f6c0****
    inline_response_200_11:
      properties:
        data:
          type: array
          items:
            type: string
            example: 默认
    inline_response_200_12:
      properties:
        collectorName:
          type: string
          example: 默认
        collectList:
          type: array
          items:
            $ref: '#/components/schemas/VideoLikeVo'
    inline_response_200_13:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/VideoLikeVo'
    like_id_body:
      properties:
        id:
          type: string
        message:
          type: string
          enum:
          - insert
          - delete
    dislike_id_body:
      properties:
        id:
          type: string
        message:
          type: string
          enum:
          - insert
          - delete

  responses:
    RegisterSuccess:
      description: 注册成功
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseBody'
          example:
            code: 200
            message: register success!
    PermissionDenied:
      description: 权限错误
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_406'
          examples:
            token失效:
              value:
                message: token失效
            越权:
              value:
                message: 没有操作权限
  requestBodies:
    UserDTO:
      description: user register
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserDTO'
      required: true
